#!/bin/sh
while read file
do
        case "$1" in
	"d")
		rm "$file" && notify-send "$file deleted." ;;


	"W")
		wal -n -q -i "$file";;
	"w")
		if [ "${file: -4}" == ".gif" ]
		then
			killall xwinwrap
			notify-send "Setting $file as Background"
			sleep 1
			wallgif "$file"
		else
			killall xwinwrap
			notify-send "Setting $file as Background"
			sleep 1
			feh --bg-scale "$file"
		fi;;
        esac
done
