#! /bin/sh


task="$HOME/.tasks"
currentLine=0

if [ ! -e "$task" ] || [ -z "$(cat "$task")" ]; then
    echo "⚒️ Tasks" > "$task"
fi

while IFS='' read -r line || [ -n "$line" ]; do
    currentLine=$(( currentLine + 1 ))

    if [ "$currentLine" -gt 1 ]; then

        end=$(echo "$line" | awk '{ print $3 }')

        if [ "$(date +%s)" -gt "$end" ]; then
            sed -i "${currentLine}d" $task
        else
            emoj=$(echo "$line" | awk '{ print $1 }')
            taskcur=$(echo "$line" | awk '{ print $2 }')
            notify-send "$emoj $taskcur"
            sleep 3
        fi
    fi
done < "$task"
