#!/bin/sh


[ -z "$1" ] && exit

if xwininfo -tree -root | grep "(\"$1\" ";
then
	echo "Window detected."

else
	echo "Window not detected... spawning."
	swaymsg "exec --no-startup-id $TERMINAL -n $1 -f $2 " && swaymsg "[instance=\"$1\"] scratchpad show; [instance=\"$1\"] move position center"

	sleep .25 # This sleep is my laziness, will fix later (needed for immediate appearance after spawn).
fi
swaymsg "[instance=\"$1\"] scratchpad show; [instance=\"$1\"] move position center"
