#!/bin/sh

ping -q -t 1 -c 1 `ip r | grep -m 1 default | cut -d ' ' -f 3` >/dev/null || exit
echo "📰 🔃" > ~/.newsup
pkill -RTMIN+6 i3blocks
/usr/bin/newsboat -x reload
echo "" > ~/.newsup
pkill -RTMIN+6 i3blocks
