#!/bin/bash

[ -z "$1" ] && exit

xwinwrap -ov -g 1360x768+0+0 -- mpv -wid WID $1 --no-osc --no-osd-bar --loop-file --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-keepaspect --no-input-default-bindings --hwdec&
