#!/bin/bash

# Use -n= to give a name

[ -z "$1" ] && exit

PNAME=$1
POSITIONAL=()

for i in "$@"
do
case $i in
	-n=*|--name=*)
	PNAME="${i#*=}"
	shift
	;;
	*)
	POSITIONAL+=("$1")
	shift
	;;
esac
done
set -- "${POSITIONAL[@]}"


if xwininfo -tree -root | grep "(\"$1\" ";
then
	echo "Window detected."

else
	echo "Window not detected... spawning."
	swaymsg "exec --no-startup-id $TERMINAL -n $PNAME $(echo "${@:2}") -e $1 " && swaymsg "[instance=\"$PNAME\"] scratchpad show; [instance=\"$PNAME\"] move position center"
	sleep .25 # This sleep is my laziness, will fix later (needed for immediate appearance after spawn).
fi
swaymsg "[instance=\"$PNAME\"] scratchpad show; [instance=\"$PNAME\"] move position center"
